In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("data files/EcommerceCustomers.csv")

In [6]:
data.shape

(500, 8)

In [7]:
data

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

In [9]:
data.describe()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
count,500.000000,500.000000,500.000000,500.000000,500.000000
mean,33.053194,12.052488,37.060445,3.533462,499.314038
std,0.992563,0.994216,1.010489,0.999278,79.314782
min,29.532429,8.508152,33.913847,0.269901,256.670582
25%,32.341822,11.388153,36.349257,2.930450,445.038277
50%,33.082008,11.983231,37.069367,3.533975,498.887875
75%,33.711985,12.753850,37.716432,4.126502,549.313828
max,36.139662,15.126994,40.005182,6.922689,765.518462

# Encoding the categorical data columns

In [13]:
data.drop(['Email','Address'],axis=1,inplace=True)

In [14]:
data

,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...
495,Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

In [15]:
encode_data = pd.get_dummies(data,columns=['Avatar'])

In [18]:
encode_data

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent,Avatar_AliceBlue,Avatar_AntiqueWhite,Avatar_Aqua,Avatar_Aquamarine,Avatar_Azure,...,Avatar_Teal,Avatar_Thistle,Avatar_Tomato,Avatar_Turquoise,Avatar_Violet,Avatar_Wheat,Avatar_White,Avatar_WhiteSmoke,Avatar_Yellow,Avatar_YellowGreen
0,34.497268,12.655651,39.577668,4.082621,587.951054,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,31.926272,11.109461,37.268959,2.664034,392.204933,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,33.000915,11.330278,37.110597,4.104543,487.547505,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,34.305557,13.717514,36.721283,3.120179,581.852344,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,33.330673,12.795189,37.536653,4.446308,599.406092,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,33.237660,13.566160,36.417985,3.746573,573.847438,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,34.702529,11.695736,37.190268,3.576526,529.049004,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,32.646777,11.499409,38.332576,4.958264,551.620145,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,33.322501,12.391423,36.840086,2.336485,456.469510,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
499,33.715981,12.418808,35.771016,2.735160,497.778642,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
boston = pd.read_csv('data files/Boston.csv')

In [20]:
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [21]:
boston.shape

(506, 14)

In [25]:
X = boston.drop(['price'],axis=1)

In [26]:
Y = boston.price

In [28]:
Y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [29]:
X.shape

(506, 13)

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0)

In [31]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [32]:
regressor.fit(X_train,Y_train)

LinearRegression()

In [33]:
predictions = regressor.predict(X_test)

In [34]:
predictions

array([24.95233283, 23.61699724, 29.20588553, 11.96070515, 21.33362042,
       19.46954895, 20.42228421, 21.52044058, 18.98954101, 19.950983  ,
        4.92468244, 16.09694058, 16.93599574,  5.33508402, 39.84434398,
       32.33549843, 22.32772572, 36.54017819, 31.03300611, 23.32172503,
       24.92086498, 24.26106474, 20.71504422, 30.45072552, 22.45009234,
        9.87470006, 17.70324412, 17.974775  , 35.69932012, 20.7940972 ,
       18.10554174, 17.68317865, 19.71354713, 23.79693873, 29.06528958,
       19.23738284, 10.97815878, 24.56199978, 17.32913052, 15.20340817,
       26.09337458, 20.87706795, 22.26187518, 15.32582693, 22.85847963,
       25.08887173, 19.74138819, 22.70744911,  9.66708558, 24.46175926,
       20.72654169, 17.52545047, 24.45596997, 30.10668865, 13.31250981,
       21.52052342, 20.65642932, 15.34285652, 13.7741129 , 22.07429287,
       17.53293957, 21.60707766, 32.91050188, 31.32796114, 17.64346364,
       32.69909854, 18.56579207, 19.32110821, 18.81256692, 23.04351442,
       22.81649956, 23.99800754, 30.62733254, 28.8662207 , 25.78198145,
        5.00689605, 36.83409088, 23.80490328, 27.36965299, 19.33057146,
       28.51439846, 19.19147448, 18.81694283, 37.94245021, 39.3441055 ,
       23.90759744, 24.95985846, 15.70262358, 25.92060968, 16.56968829,
       15.76303806, 12.89190083, 24.4389405 , 30.9319885 , 22.36798609,
       20.17628607,  0.22819711, 25.26459847, 15.35369364, 17.7983399 ,
       25.44689554, 22.46612234, 32.57911019, 22.01436262, 27.37542798,
       23.31348039,  6.29811532, 14.75925592, 22.44945223, 29.11172812,
       32.97160856, 12.85457141, 19.79963356, 20.60017439, 12.06928939,
       23.38532482,  4.75243811, 19.8342911 ,  9.17555571, 44.63299931,
       30.63144603, 12.29971299, 17.53804831, 21.50222331, 23.63281301,
       20.28259817, 35.17973368])

In [36]:
pd.DataFrame({'Actual':Y_test,'Predicted':predictions})

     Actual  Predicted
329    22.6  24.952333
371    50.0  23.616997
219    23.0  29.205886
403     8.3  11.960705
78     21.2  21.333620
..      ...        ...
49     19.4  17.538048
498    21.2  21.502223
309    20.3  23.632813
124    18.8  20.282598
306    33.4  35.179734

[127 rows x 2 columns]

In [38]:
from sklearn.metrics import r2_score
r2_score(Y_test,predictions)

0.6354638433202138

In [39]:
X.max()

crim        88.9762
zn         100.0000
indus       27.7400
chas         1.0000
nox          0.8710
rm           8.7800
age        100.0000
dis         12.1265
rad         24.0000
tax        711.0000
ptratio     22.0000
black      396.9000
lstat       37.9700
dtype: float64

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [54]:
X = scaler.fit_transform(X)

In [58]:
X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0)

In [60]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [61]:
regressor.fit(X_train,Y_train)

LinearRegression()

In [62]:
predictions = regressor.predict(X_test)

In [63]:
r2_score(Y_test,predictions)

0.6354638433202131

In [64]:
from sklearn.linear_model import Lasso

In [ ]:
lasso = Lasso(alpha=1)

In [65]:
lasso.fit(X_train,Y_train)

Lasso(alpha=1)

In [66]:
predictions = lasso.predict(X_test)

In [68]:
print(r2_score(Y_test,predictions))

0.5637285811120971